### ISSUE TITLE
How to select multiple Record and delete them from REDCap permanently? 

### ISSUE THREAD

**Issue by vinotharyan** [redcap-tools/PyCap#101]
Current we planning deleted multiple records which around 10000 Records which need to deleted from REDCap is they a way to select multiple RECORD based on record id and delete them. by using API?

**Comment by vinotharyan** [comment]
@sburns is their way to delete multiple records.

**Comment by sburns** [comment]
I don't believe so, at the time I wrote pycap, if I recall, the REDCap developers considered automated deletion dangerous functionality.
