### ISSUE TITLE
TypeError with force_auto_number during record import

### ISSUE THREAD

**Issue by saraputnam** [redcap-tools/PyCap#102]
I am using PyCap to import records into a project with auto-numbering for records enabled.  However, when I use _force_auto_number='True'_, I get the following TypeError:

`TypeError: import_records() got an unexpected keyword argument 'force_auto_number'`

I am using REDCap version 8.10.20.  Are there any reasons why this error would be occurring?

Thanks
Sara

**Comment by sburns** [comment]
I'm guessing we haven't implemented what appears like a new parameter of the API.

**Comment by martinburchell** [comment]
It was added in https://github.com/redcap-tools/PyCap/commit/1b956406369ad24c0125b43e6dcfb5d88c326147

but this won't be in the version on PyPI

**Comment by pwildenhain** [comment]
Linking this to #89 so so that we know this can be closed when it is closed.

**Comment by pwildenhain** [comment]
🎉 Released to pypi 1️⃣ . 1️⃣ . 0️⃣
