### ISSUE TITLE
Contributing to PyCap

### ISSUE THREAD

**Issue by pwildenhain** [redcap-tools/PyCap#109]
👋 Hey @sburns !
cc: @gammaflauge

Wasn't sure of the best way to start this conversation, let me know if you don't think an issue is appropriate for this; we're happy to meet for a phone chat, or set up an email chain.

Excited to be able to help contribute 🙌 and want to figure out the best way to us to get started.

**Comment by pwildenhain** [comment]
Hello again @sburns 

What do you think is the best way for us to get started with contributing to `PyCap`?

**Comment by sburns** [comment]
Would you mind sending an email to `scott.s.burns` at google's email domain?

**Comment by pwildenhain** [comment]
Hey @sburns I sent an email a little over a week ago, did you get it?

**Comment by sburns** [comment]
I did, just bad at email :( I'll try to send you something tonight

**Comment by pwildenhain** [comment]
🙏 Hope you're doing well during this crazy time. 

Would you like to continue to try and chat over email? Or would you be able to make me a contributor to this repo and I can just get started?

I understand if you're indisposed right now, so I created a [fork](https://github.com/pwildenhain/PyCap) to start working on outstanding issues. I was thinking about getting started with #87, #74, #77 since those seem _relatively_ simple 🤞 to tackle

**Comment by pwildenhain** [comment]
Thanks for granting me access 🙇 I'll get to work 👍
