### ISSUE TITLE
Function export_project_info(format='json') not working or showing up when install the PyCap on Jupyter Notebook

### ISSUE THREAD

**Issue by xd3262nd** [redcap-tools/PyCap#114]
Hello, 

I saw the `export_project_info(format='json')` function is on the repo but it does not show up when I installed it. Please let me know how can I fix this issues or any other way to grab the project info from redcap.

**Comment by sburns** [comment]
How did you install PyCap?

**Comment by xd3262nd** [comment]
I install PyCap with pip install PyCap command

Regards,
Qian
________________________________

**Comment by sburns** [comment]
Yeah I'm pretty sure the `export_project_info` is only in master, you might try installing with `$ pip install -e git+https://github.com/redcap-tools/PyCap.git#egg=PyCap`

**Comment by pwildenhain** [comment]
@xd3262nd Did this work for you?

**Comment by xd3262nd** [comment]
@pwildenhain yes sorry forgot to reply I will close the issue then :) thanks again
