### ISSUE TITLE
cannot install version 1.1.0 on Ubuntu, __init_.py is DOS not Unix

### ISSUE THREAD

**Issue by fissell** [redcap-tools/PyCap#121]
Hi,

I tried installing PyCap-1.1.0 with the standard pip2 install PyCap command on an Ubuntu 20.04 system with Python 2.7.18.
I got the error:

2020-08-07T17:05:29,524     Running command python setup.py egg_info
2020-08-07T17:05:29,649     Traceback (most recent call last):
2020-08-07T17:05:29,650       File "<string>", line 1, in <module>
2020-08-07T17:05:29,650       File "/tmp/pip-install-TlsDNa/pycap/setup.py", line 49, in <module>
2020-08-07T17:05:29,650         version=find_version("redcap", "__init__.py"),
2020-08-07T17:05:29,650       File "/tmp/pip-install-TlsDNa/pycap/setup.py", line 25, in find_version
2020-08-07T17:05:29,651         raise RuntimeError("Unable to find version string.")
2020-08-07T17:05:29,651     RuntimeError: Unable to find version string.
2020-08-07T17:05:29,659 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I looked at the code and I think the issue is that the __init__.py file is for DOS not Unix and its end of line char is \r\n not \n
and this breaks the re.search() for the version string.

Ran snippets in ipython:
setup code modified to take away the EOL constraint by removing $ finds the version string:
```
In [33]:  version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]", version_file, re.M)
In [34]: version_match.group(1)
Out[34]: '1.1.0'

```
Existing code does not find the version string"
```
In [35]:  version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]$", version_file, re.M)
----> 1 version_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Print of version_file read of __init__.py:
In [38]: version_file
Out[38]: '#!/usr/bin/env python\r\n# -*- coding: utf-8 -*-\r\n\r\n__author__ = \'Scott Burns <scott.s.burns@gmail.com>\'\r\n__license__ = \'MIT\'\r\n__copyright__ = \'2014, Vanderbilt University\'\r\n__version__ = \'1.1.0\'\r\n\r\n"""\r\nThis module exposes the REDCap API through the Project class. Instantiate the\r\nclass with the URL to your REDCap system along with an API key, probably\r\ngenerated for you by a REDCap administrator.\r\n\r\nWith a Project object, you can view the metadata and export/import data.\r\n\r\nOther API requests are available, such as exporting users & Form-Event Mappings.\r\n\r\n"""\r\n\r\nfrom .project import Project\r\nfrom .request import RCRequest, RCAPIError, RedcapError\r\n'

How do you handle DOS vs Unix and how can I install a Unix compatible version ?

thanks very much for all your work !
Kate

**Comment by pwildenhain** [comment]
Haha so much effort to be clever and not have to document the package version in two places. I'll check and see if the version string is still found by removing those restrictions.

**Comment by pwildenhain** [comment]
Can you try installing from the `fix-package-version-for-unix` branch and let me know if that works for you? If so, I'll cut a patch release to PyPI

**Comment by fissell** [comment]
Hi,

That worked !!!

thanks very much,
Kate
________________________________

**Comment by pwildenhain** [comment]
Check out the newest version on pypi here: https://pypi.org/project/PyCap/1.1.1/
