### ISSUE TITLE
Release for 1.1.2?

### ISSUE THREAD

**Issue by tobiasmcnulty** [redcap-tools/PyCap#126]
Hello, and thank you for this project!

Would it be possible to upload a release for 1.1.2 to PyPI? I've tested the new `date_begin` filter option to `export_records()` and it works as expected.

**Comment by pwildenhain** [comment]
Sure thing -- we can aim to release some time next week 👍

**Comment by tobiasmcnulty** [comment]
I appreciate it, thank you!

**Comment by tobiasmcnulty** [comment]
Thank you!!
