### ISSUE TITLE
Change "Form Status" when importing record

### ISSUE THREAD

**Issue by LivingDeadCloud** [redcap-tools/PyCap#137]
Hello Everybody

First of all, I'm not exactly sure if this is the correct way to answer a question, if it's not, I apologize.

That said, I just started to use REDCap (total noob until yesterday), I was able to connect to my local REDCap server (I'm just using it for test), and I was able to import data to it.
I have a field, not created by me (I guess it's some kind of default field) which is called "Form Status". If I manually add a new record, I can select 1 out of 3 values, which are "Complete, "Incomplete", "Unverified". If I add one record by importing it with Python, it is added as "Incomplete". I am posting a screenshot as well to show you what I mean:

![Screenshot from 2020-11-20 17-29-28](https://user-images.githubusercontent.com/22834605/99824458-079f6300-2b56-11eb-938e-404a7e8f00c5.png)

So question is the following: is there a way to mark the new record I add as "Complete" programmatically?

I looked it up in the documentation, but I was not able to find it. So I'm not sure it can be done either.

Thanks a lot to everyone who will answer to this.

Have a nice weekend

**Comment by pwildenhain** [comment]
Hey there 👋

Questions are always welcome here -- though it might be a while before someone gets to it.

To answer your question, that is an auto generated field that comes with each form, keeping track of whether or not the form is complete.

If you want data you import to be marked complete, I believe you need to import that field, for each imported record with a value of "2"

If this doesn't work I would recommend reaching out to the REDCap administrator at your site to get more information. This project is not _officially_ affiliated with REDCap, and your administrators should know everything you'll need

🙏 Hope this helps

**Comment by LivingDeadCloud** [comment]
Dear @pwildenhain 

I tried that myself and I confirm it works.

Thanks a lot (and great work btw)!
