### ISSUE TITLE
Simple Import isnt working 

### ISSUE THREAD

**Issue by rmcbarnett** [redcap-tools/PyCap#138]
I just cannot get the import functionality to work lol. I always get back {'count': 0}
My code is simple enough: 

project = Project(URL, API_KEY)
data = {'cr_record_id': '1', 'cr_lat': '50.5', 'cr_long': '123.1'}
json_data = json.dumps(data)
response = project.import_records(json_data, overwrite='overwrite', format='json')

( Not the main issue, but I had to use json dumps because I kept getting this error when I tried to import the data:
Requests.exceptions.RequestException: {'error': '"1","cr_lat","50.5","The value you provided could not be validated because it does not follow the expected format. Please try again.) 

Anyway, the above code compiles, I just dont get why it isn't updating the record in redcap or creating new ones when i change the value for cr_record_id. 
I looked at issue 103 (https://github.com/redcap-tools/PyCap/issues/103) , where the solution was to place data in "[]". That didn't work for me either. 

I also saw in issue 103 that @sburns asked if the person is importing a record that contains the default field. I assume the default field is cr_record_id but how do i determine this for sure? 

I also checked that I have API permissions to export and import/update. The API token is also correct

Can anyone tell me what I am doing wrong? I've spent two days on what looks to be a very simple record update.

**Comment by sburns** [comment]
1. You should not json-encode your data before sending to import_records. Behind the scenes the data is json-encoded, you don't want to double encode it. 
2. Your data should be an array of dictionaries, not a single dictionary.
3. The primary field can be found in the UI and also on the Project instance (I think).

**Comment by rmcbarnett** [comment]
Thanks for the quick response! Thanks the change kind of worked.. but still a bit of an issue..

This code updates the record: 

data = {'cr_record_id': '1', 'cr_lat': '52.126'}
response = project.import_records([data], overwrite='overwrite', format='json')

But when i try to add in another field it fails.. 
data = {'cr_record_id': '1', 'cr_lat': '52.126', 'cr_long': '122.6'}
response = project.import_records([data], overwrite='overwrite', format='json')

Error:   raise RedcapError(str(response))
requests.exceptions.RequestException: {'error': '"1","cr_long","122.6","The value you provided could not be validated because it does not follow the expected format. Please try again."'}

**Comment by rmcbarnett** [comment]
Actually never mind, that would be an issue on my end because adding other fields appear to work. Thanks for the tip on  nixing the json dump!

**Comment by rmcbarnett** [comment]
@sburns  sorry to reopen this but needed some further help.. New to python and to redcap..So the struggle is real..
You said above that "Your data should be an array of dictionaries, not a single dictionary.".

Could you give me an example of how to create that array and pass it to "import records"? Nothing I try is working. My code is below. Basically my end game is to populate an array of dictionaries on the fly as I map values (lots of data manipulation) from a csv. I can take care of reading from the csv and mapping. My issue is just creating an array of dictionaries with the mapped values. What would make my hard coded array of dictionaries below work? If  i get the syntax right I can take it from there...

data = [{}]

data[1] = {'cr_record_id': '3', 'cr_lat': '52.126', 'cr_long': '122.600', 'cr_datum': '2', 'cr_epdt': str(my_date),
        'cr_tx': '1', 'cr_callnum': '', 'cr_loctyp': '11', 'cr_estageu': '0', 'cr_estagev': '39', 'cr_agecat': "",
        'cr_sexp': '0', 'cr_v1sl': '1', 'cr_pdisp': '1', 'cr_witbys': '1', 'cr_dspcno___1': '1'}

data[2] = {'cr_record_id': '4', 'cr_lat': '52.126', 'cr_long': '122.600', 'cr_datum': '2', 'cr_epdt': str(my_date),
        'cr_tx': '1', 'cr_callnum': '', 'cr_loctyp': '11', 'cr_estageu': '0', 'cr_estagev': '39', 'cr_agecat': "",
        'cr_sexp': '0', 'cr_v1sl': '1', 'cr_pdisp': '1', 'cr_witbys': '1', 'cr_dspcno___1': '1'}


response = project.import_records(data, overwrite='overwrite', format='json')

Error: list assignment index out of range

**Comment by rmcbarnett** [comment]
By trial and error, this actually seemed to work , but let me know if there is a better way: 

data = {}
data[1] = {'cr_record_id': '4', 'cr_lat': '52.126', 'cr_long': '122.600', 'cr_datum': '2', 'cr_epdt': str(my_date),
        'cr_tx': '1', 'cr_callnum': '', 'cr_loctyp': '11', 'cr_estageu': '0', 'cr_estagev': '39', 'cr_agecat': "",
        'cr_sexp': '0', 'cr_v1sl': '1', 'cr_pdisp': '1', 'cr_witbys': '1', 'cr_dspcno___1': '1'}

data[2] = {'cr_record_id': '5', 'cr_lat': '52.126', 'cr_long': '122.600', 'cr_datum': '2', 'cr_epdt': str(my_date),
        'cr_tx': '1', 'cr_callnum': '', 'cr_loctyp': '11', 'cr_estageu': '0', 'cr_estagev': '39', 'cr_agecat': "",
        'cr_sexp': '0', 'cr_v1sl': '1', 'cr_pdisp': '1', 'cr_witbys': '1', 'cr_dspcno___1': '1'}


response = project.import_records(data, overwrite='overwrite', format='json')

**Comment by sburns** [comment]
I can't say why this works, but I think you're looking for `data = []`. The object that you import should be an array, denoted by square brackets. Also python arrays are 0-indexed so `data[1] =....` should be `data[0] = ...` and so forth.

**Comment by pwildenhain** [comment]
@rmcbarnett I'm going to close this since it's out of scope for the package. Feel free to continue to comment however, and people may be able to jump in and help troubleshoot your issues.

**Comment by rmcbarnett** [comment]
Problem is once issues are closed, answers will not be given as the issue is now hidden. (Anyway I already figured it out on my own. For anyone struggling see code snippet below)
Is there another place to post questions about using the redcap project? I am new to the project and sometimes have questions. The documentation Is good but is short of a lot of examples.
Now I’m worried that everytime I have a question, this guy is going to close it. 

s=0
Loop:(for or while)
  ArrayDict = []
  ArrayDictRow = {}
  ArrayDict.append(ArrayDictRow) 
  ArrayDict[s][‘recordfield’] = value 
  ArrayDict[s][‘recordfield2’] = value2
  s+=1 

response = project.importrecords(ArrayDict, format=json)

**Comment by pwildenhain** [comment]
> Is there another place to post questions about using the redcap project? I am new to the project and sometimes have questions.

I get this. I know what it's like to be a new user of a sparsely documented tool. I know that it can be confusing and frustrating.

GitHub is a code collaboration platform, and operates best in that narrow scope. Issues should be related to code/documentation changes (whether features or bugs).

I think what you are expressing the desire for is a developer _community_ -- where you can ask each other questions, troubleshoot together, etc. The tools that handle this best are slack, gitter, a subreddit, etc.

If a community is what you want, then it's a great opportunity to start one. I would happily join it and reference it in the official documentation.

If you want better examples in the documentation itself, then file an issue to that effect. We can work together on creating more effective examples.

**Comment by wefatherley** [comment]
Hi @rmcbarnett,

When specifying JSON array in Python, one declares a list:
```python
data = []
```
To add REDCap records (JSON objects), use the list's append method like this:
```python
data.append( {"my": "redcap", "project": "record"} )
```
As helpful clarification, the reason `IndexError` is raised is because the notation `data[i]` is for getting the `i`th item from `data`, and never for setting it. For instance, if `data = []`, it's not possible to get the `i`th item from it because there are no items in it.


To that end, maybe this issue could be reopened, whereby the fix would be for the import machinery to accept any sort of valid JSON, or any JSON-serializable Python object, and perform itself the task of making sure import data are appropriately nested in an array?

**Comment by rmcbarnett** [comment]
Hi to get around this, I append the record item first to data then change the record, then import. So I end up with a list of json objects.
Data = []
Record ={}
Data.append (record)

I used a counter to keep track of  the latest record to update.
Data[counter][record field] = record field value.

Sent from my iPhone

On 20 Apr 2021, at 11:46 AM, Will Fatherley ***@***.***> wrote:

﻿

Hi @rmcbarnett<https://github.com/rmcbarnett>,

When specifying JSON array in Python, one declares a list:

data = []

To add REDCap records (JSON objects), use the list's append method like this:

data.append( {"my": "redcap", "project": "record"} )

As helpful clarification, the reason IndexError is raised is because the notation data[i] is for getting the ith item from data, and never for setting it. For instance, if data = [], it's not possible to get the ith item from it because there are no items in it.

To that end, maybe this issue could be reopened, whereby the fix would be for the import machinery to accept any sort of valid JSON, or any JSON-serializable Python object, and perform itself the task of making sure import data are appropriately nested in an array?
