### ISSUE TITLE
Updating RedCap Hidden field using import records

### ISSUE THREAD

**Issue by rmcbarnett** [redcap-tools/PyCap#139]
Is there a way to update a form field (cr_dspcno) that is conditionally hidden? 

This is my code: 
data = {'cr_record_id': '1', 'cr_lat': '52.126', 'cr_long': '122.600', 'cr_datum': '2', 'cr_epdt': str(my_date),
        'cr_tx': '1', 'cr_callnum': '', 'cr_loctyp': '11', 'cr_estageu': '0', 'cr_estagev': '39', 'cr_agecat': "",
        'cr_sexp': '0', 'cr_v1sl': '1', 'cr_pdisp': '1', 'cr_witbys': '1', 'cr_dspcno': "1"
        }
response = project.import_records([data], overwrite='overwrite', format='json')
I keep getting this error: 

{'error': 'The following fields were not found in the project as real data fields: cr_dspcno'}

This happens whether the condition for visibility on the form has been filled or not.

**Comment by rmcbarnett** [comment]
K, Solved this, the data dictionary had an alternate name, which was the same as the associated hidden checkbox, cr_dspcno___1.

**Comment by pwildenhain** [comment]
Yeah, checkbox names are tricky, nice find 🕵️
