### ISSUE TITLE
User API token cause {'error': 'You do not have permissions to use the API'}

### ISSUE THREAD

**Issue by LivingDeadCloud** [redcap-tools/PyCap#140]
Hello everybody

I'm doing some test with my REDCap project, and I found out that user API does not give me access to data.

Here's what I did. I created a new project as site_admin, I created site_admin's token and I can export/import data programmatically without problems. Then I tried to create a new user (which I gave all permissions I am aware of, see bottom of post), and I tried to do the same operations. Sadly, it is not working.

With this line of code:
project = Project(URL, API_KEY, verify_ssl=False)
The error I get is: "RequestException: Exporting metadata failed. Check your URL and token."

If I try to access with Lazy mode:
project = Project(URL, API_KEY, verify_ssl=False, lazy=True)
The error I mentioned before is not raised, but when I try to export data, I get "{'error': 'You do not have permissions to use the API'}".

My question is: is it possible to export/import data with non-admin API token? If this is the case, I guess I'm messing something up with user permissions. Or maybe it is not possible and that is never going to work.

Here are the settings of the user:
![REDCap_crop2](https://user-images.githubusercontent.com/22834605/102065021-4ee8de80-3df8-11eb-84e0-be061ded597b.png)
![REDCap_crop1](https://user-images.githubusercontent.com/22834605/102065003-4a242a80-3df8-11eb-9415-b1996233bf99.png)

Thanks everyone for your time!

**Comment by pwildenhain** [comment]
Hi there 👋

It's definitely possible to pull data without an admin token. Seems like something is wrong with the REDCap / Project configuration.

Since this isn't a `PyCap` issue, I would recommend reaching out to REDCap to ask for further assistance. If you figure it out, feel free to post back here, where others could discover your solution

**Comment by LivingDeadCloud** [comment]
I asked for help on the official forum and this is the answer (I hope it's not a problem to copy-paste it):

"Your mentioning “site_admin” implies that you didn’t set any authentication (authentication = ‘none’ in Control Center). This means that the only user having any access rights is hard-coded site_admin. So your user “utente_base” (BTW, usernames should be all lower case) doesn’t have rights to anything, no matter what you granted - because it is not authenticated. You need to make sure your server can send emails, create user (or resend the password email), then switch authentication to 'Table', and let the user set password. Before changing Authentication you better make him administrator.
then, once the user is able to successfully log in, his API tokens will start working."

I haven't tried that myself but hopefully I will in the next days and I will let you know if it works.

Cheers
