### ISSUE TITLE
"exists on an instrument that is not designated..."

### ISSUE THREAD

**Issue by chrisdanamalone** [redcap-tools/PyCap#142]
I am receiving an error when trying to upload data to fields in Redcap. I am administering a series of surveys and they must be scored and the scores written to specific fields in Redcap. 

The error reads: "RequestException: {'error': '"testss","corona_2","2","This field (\'corona_2\') exists on an instrument that is not designated for the event named \'Screening (Arm 1: HeiSIS Screening)\'. You are not allowed to import data for this field into this event."'}"

I am not trying to upload any files, just write data to a series of fields in the database. My code is below. Can you please tell me how to fix this? 

thanks, 
Chris

from redcap import Project, RedcapError

api_key = *********** (censored)
api_url = ***********

redcap_data = Project(api_url, api_key)
data_therapy = redcap_data.export_records(test_sub)

data = [{'record_id': 'testss', 'corona_2': 2}]
response = redcap_data.import_records(data, overwrite='overwrite', format='json')

**Comment by chrisdanamalone** [comment]
I think I narrowed the problem down to not identifying the event in my longitudinal study correctly. What is the correct formatting for importing records to a specific event in a longitudinal study? For testing, the mapping I need to access is: {'arm_num': 1, 'unique_event_name': 't0_questionnaires_arm_1', 'form': 'corona_fragebogen'}

How should I incorporate this mapping into my import _records statement? the subject id and the field are in the code below

data = [{'record_id': 'testss', 'corona_2': 1}]
num_processed = redcap_data.import_records(data, overwrite='overwrite', format='csv')
print(num_processed)

**Comment by pwildenhain** [comment]
Hi there 😁 and welcome to the project. It sounds like you are facing issues with the API itself -- which is totally understandable! 

I would recommend checking out the python code in the "API Playground" section of REDCap for the the "Import records" method for this instrument you are referring to.

By taking a cursory look at your code, I believe the `arm_num` and the `uniqie_event_name` are required fields for data import, but I don't see them in the sample import code you shared

**Comment by chrisdanamalone** [comment]
Thank you for your feedback! I was able to get it to work by changing the script to: 

for i in range(n_fields):
    to_import = [{'record_id': sub1, 'redcap_event_name': 't0_questionnaires_arm_1', fields_for_upload[i]: data_to_upload[i]}]
    response = redcap_data.import_records(to_import)
    print(response)
