### ISSUE TITLE
Export Records with filter example

### ISSUE THREAD

**Issue by rmcbarnett** [redcap-tools/PyCap#143]
Im trying to export records with a filter on the recordID. How do I do this? 
Some of the record IDs (name of record ID is 'cr_recordID') contain an identifier attached to the end = 1BC, 2BC, 3BC etc. I would like to export only those records with a 'BC' at the end. 

In the documentation, I'm seeing a filter_logic:string option with no example. Could someone please tell me how to achieve what I want using this? 

This is what I am doing so far: 
 fields1 = ['cr_cmprt1','cr_cmprt2','cr_cmprt3','cr_cmprt4','cr_cmprt5','cr_cmprt6','cr_cmprt7','cr_cmprt8','cr_cmprt9','cr_cmprt10']

  df = project.export_records(format='df',fields=fields1 )

**Comment by pwildenhain** [comment]
The `fields` parameter refers to the _columns_ of your data set, not the rows.  If you want to only have records that end with that suffix, I think the best way would be. The export the whole data set, and then filter it down with `pandas` (or some other python tool)

Given that this is not a package issue, I'm going to close it. Feel free to continue commenting however

**Comment by rmcbarnett** [comment]
A lot of the “issues” recorded here are people asking for how tos. 
You also misread my question before closing my issue. I know what the fields parameter does, I was asking what the filter logic option does and an example of how to use it to filter records.

**Comment by pwildenhain** [comment]
I'm aware that a lot of the issues here are 'how-to's'. My saying this was not a criticism of you, it was a statement and a justification for closing the issue.

Typically for those 'how-to' issues, we refer people to the REDCap API documentation or the API Playground, that comes with each REDCap installation.

The `filterLogic` parameter is implemented by the API itself, not this package. We simply pass that parameter along to the API for you.

I did misread your question, though my advice remains the same. I'm pretty sure that you cannot use `filterLogic` to only get records that end in `BC`. You could use it do something like, 'give me records where the value of this column is less than 10' but nothing more advanced than that. You're better of using something like `pandas` to do the more advanced filtering after the export.

However, this is all just from my memory, the API documentation would be a more reliable source.

**Comment by rmcbarnett** [comment]
Thanks
