### ISSUE TITLE
Importing with Field Labels

### ISSUE THREAD

**Issue by TriassicSalamander** [redcap-tools/PyCap#152]
After having exported records with labels rather than raw values, I am now trying to import these records back to my redcap project.
I'm getting a RequestException saying that the values for a particular field are not valid. For this field, the raw values are either 1 or 0 and the label values are either 'Complete' or 'Incomplete'.

If I try export then import using raw values, there is no issue.

I'm wondering if this is something that PyCap supports or if the issue is at my end.
If more information is required, please let me know.

**Comment by pwildenhain** [comment]
The REDCap API only supports importing data in **raw** format, it doesn't support labels.

Welcome to `PyCap` feel free to add any issues related to other bugs that come up, or requested features.
