### ISSUE TITLE
filter_logic format in export API

### ISSUE THREAD

**Issue by jthomas08** [redcap-tools/PyCap#155]
Can share an example of the format for the filter_logic parameter in export_records? I can't seem to get it export the correct records.

**Comment by pwildenhain** [comment]
Sure, can you post what’s currently more working for you?

Also FYI we’re not affiliated with REDCap. Just some nerds who built a thing to interface with the REDCap API — but we’ll do our best to answer your questions

**Comment by jthomas08** [comment]
I got it, looks like the filter param is a pure string, I used:**filter_logic="[respiratory_specimen_results_form_complete]='2'")**

I tried to use pythonic primitives like == , thanks for all the work you all do for this, makes life easier..
