### ISSUE TITLE
Can't import file

### ISSUE THREAD

**Issue by aegoff** [redcap-tools/PyCap#156]
When I try to instantiate a project, like this:
`import requests`
`from requests import post `
`import redcap `
`from redcap import Project, RedcapError` 

`url='https://redcap.......edu/redcap/api/'`
`key=os.getenv("TOKEN")`
`project=Project(url,key,verify_ssl=False,lazy=False)
`
I get this error: "KeyError: 'Key not found in metadata"

When I turn on lazy loading, it works just fine, until I want to import a file. 

`filename='something.wav'`
`field='files'`
`with open(filename, 'rb') as f:`
`		project.import_file(record='1',field=field, fname=filename, fobj=f)`

I get this error: 
`"File "C:\.....\src\pycap\redcap\project.py", line 833, in _check_file_field`
`    is_field = field in self.field_names`
`TypeError: argument of type 'NoneType' is not iter`

Whether I turned lazy loading off or on, I'm still screwed. I also double-checked, and I have the most up-to-data version of PyCap from github, not from pypi. Then, I just gave up with pycap and tried requests.  

`dataFile = {'token': key, 'content': 'audio/wav', 'action': 'import', 'record': pid, 'field': 'filez','event': '','returnFormat': 'json'}`
`file = open("something.wav","rb")`
`rf = requests.post(url, data=dataFile, files={'file':file}, verify=False)`
`file.close()`
`print(rf.status_code)`

...Which printed a 200 HTML response but no data was uploaded to REDCap. 

Please, if someone has any idea what might be going wrong with this, please let me know.

**Comment by pwildenhain** [comment]
Just getting to this now -- is this error limited strictly to importing a file? Have you tried exporting a file with requests, and seeing what happens?

Also, just at first glance, the api url looks a little off to me, just based off the different REDCap servers I've seen. Usually it's something like `https://redcap.domain.edu/api/`

**Comment by pwildenhain** [comment]
There have been lots of changes made recently to how the internal of the package work (preparing for version 2.0 release). I'm going to close this issue for now, but please feel free to open it again, if the issue persists after using the updated version of `PyCap`
