### ISSUE TITLE
Command-line scripts?

### ISSUE THREAD

**Issue by njvack** [redcap-tools/PyCap#157]
Hey there!

We're looking at writing a couple of general-purpose command-line utilities on top of pycap: a generic CSV data importer and a CSV data exporter.

The importer would be super simple — just read a CSV file and import into REDCap; longitudinal and repeated instrument fields would be on the CSV file creator to add.

The exporter would be a little bit more complicated — we want to return one row per ppt (though I guess we could postprocess that out, hmmm) so there's a bit of jiggling to get the data to come out and not look "weird."

Anyhow! Would you potentially be interested in including these in pycap? If so, do you mind a dependency on pandas?

Thanks!

**Comment by pwildenhain** [comment]
This sounds like it'll be really useful 👍

I'm going to refactor the code base in the near future, most notably dropping python 2 support.

pandas is already in the "extra_requires" so having a dependency on that shouldn't be a problem.

Can I ping you again once that work is underway?

**Comment by njvack** [comment]
No problem! Death to python 2!

**Comment by pwildenhain** [comment]
Hey @njvack they infrastructure is pretty much set at this point -- I decided to go with `poetry` for package development/management.

Here's the [docs]( https://python-poetry.org/docs/) if you're unfamilar. There's also the [`CONTRIBUTING.md`](https://github.com/redcap-tools/PyCap/blob/master/CONTRIBUTING.md) docs. And specifically here's a section on installation of [console scripts](https://python-poetry.org/docs/pyproject/#scripts)

**Comment by pwildenhain** [comment]
2.0 has been released 🎉

**Comment by pwildenhain** [comment]
Hey @njvack I'm going to close this issue out for now, just for repo housekeeping purposes. Feel free to reopen if you would still like to collaborate

**Comment by pwildenhain** [comment]
Sounds great. If you want, we can just start with the simple one and added more features as we go along. No need to have perfect code before starting the convo. Wishing you the best 👍🏻
