### ISSUE TITLE
export logging API

### ISSUE THREAD

**Issue by jthomas08** [redcap-tools/PyCap#158]
There's now support for export logging filtered on dates, users, as an API etc, can that feature be added...thnx

**Comment by pwildenhain** [comment]
I plan to add this before releasing version 2 (soon hopefully 🤞🏻 )

**Comment by pwildenhain** [comment]
So I didn't get this in before releasing version 2.0 (which was released yesterday).

But it will be add in #222, and will eventually be included in version 2.1
