### ISSUE TITLE
Consider dropping support for older REDCap servers

### ISSUE THREAD

**Issue by pwildenhain** [redcap-tools/PyCap#167]
This comment makes me wonder if we should only support more modern servers as part of the new release:

https://github.com/redcap-tools/PyCap/blob/3ea897886b7ea94421461d0be89ecb6ac094286c/redcap/project.py#L512-L517

**Comment by pwildenhain** [comment]
@wibeasley What's your policy/approach to this problem with REDCapR?

**Comment by wibeasley** [comment]
So far, we haven't encountered any REDCap update that considerably broke any REDCapR functionality.  There were a few little things in 2014 with the jump to V6.0.  Then a little modification  was necessary [two years later with a new line after the token](https://github.com/OuhscBbmc/REDCapR/issues/103).  In both cases, we were able to adapt REDCapR code to fit both sides of the change.

But that's certainly not guaranteed forever.  One option is to [tag ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags) the commit of the last version of PyCap release to support the old version of REDCap, and then encourage everyone to upgrade the server & PyCap.

From the user's perspective, a gentler approach would be to query the REDCap version (there's a dedicated API call for that), then invisibly dispatch the user to the new way or the old way.  But then you probably won't have two versions of the server to run your test suite against.

In the future, if there was something that broke capability, @talyorr4 had a really good reason.

**Comment by pwildenhain** [comment]
Ok great, that's all really good to know. I think we'll go with a "wipe" the slate clean approach, where we just support more current servers (like >6.0) and then we can always in workarounds for any future breaking changes.
