### ISSUE TITLE
PyCap 2.0 design thoughts

### ISSUE THREAD

**Issue by pwildenhain** [redcap-tools/PyCap#174]
Would love for @sburns @wibeasley @martinburchell @pbchase to chime in here if you can ❤️ 

Right now we have the God class `Project` 👼🏻 which is convenient for users, but tough for developers to get a grasp on what is going on.

Since REDCap divides their API into sections, why don't we do that as well? Break out into smaller classes for each section of the API playground? Then we can still combine at the end to get the `Project` class to make life easier for the users.

<img width="850" alt="Screen Shot 2021-11-18 at 12 04 44 PM" src="https://user-images.githubusercontent.com/35195136/142462906-49da2872-6d5e-45bb-8fc7-3edad30b08ec.png">

```python
class _BaseRedcapAPI:

    def __init__(self, url, token) -> None:
        self.url = url
        self.token = token
    

    def call_api(self, request: str) -> str:
        return f"Request is {request}"


class RecordsAPI(_BaseRedcapAPI):

    def export_records(self):
        res = self.call_api("export records")
        print(res)
        return [
            {"record_id": 1, "field_1": 1},
            {"record_id": 2, "field_1": 2},
        ]


class MetadataAPI(_BaseRedcapAPI):

    def export_metadata(self):
        res = self.call_api("export metadata")
        print(res)
        return [
            {"field_name": "record_id", "type": "text"},
            {"field_name": "field_1", "type": "number"},
        ]


class Project(RecordsAPI, MetadataAPI):
    
    def __init__(self, url, token):
        self.metadata = super().export_metadata()


records_api = RecordsAPI(url="https://redcap.chop.edu/api/", token="mytoken")
metadata_api = MetadataAPI(url="https://redcap.chop.edu/api/", token="mytoken")
redcap_project = Project(url="https://redcap.chop.edu/api/", token="mytoken")

assert redcap_project.export_records() == records_api.export_records()
assert redcap_project.metadata == metadata_api.export_metadata()
```

**Comment by wibeasley** [comment]
Sorry I'm responding only with questions to your question...

I'm good developing C#/Java classes & inheritance.  But not with Python.  Grain of salt.
1. I see how the two smaller classes (`RecordsAPI` & `MetadataAPI`) combine together to form the God class (`Project`).  Is this conventional in the Python world?
2. How would this help the developers grasp the complexity?  As a developer, it seems like now I have to learn & remember which functions are nested in which (super?)class.
3. What are the tradeoffs?
4. Any chance the categorization could be cosmetic?  Like our the function are categorized int he API playground, or how [pkgdown encourages categorizing](https://ouhscbbmc.github.io/REDCapR/reference/) functions/methods?
5. In Python, can [the large class](https://github.com/redcap-tools/PyCap/blob/master/redcap/project.py) be split across different files?  (Like how R's functions can be defined in different files, then brought together as S3 methods in the class)?

**Comment by martinburchell** [comment]
@pwildenhain thanks for including me in this discussion.

 [Our REDCap integration](https://github.com/RudolfCardinal/camcops/blob/master/server/camcops_server/cc_modules/cc_redcap.py) is available but as far as I know has not yet been thoroughly tested in production. My main issues were with the REDCap API itself rather than anything PyCap related. Anything I couldn't do with PyCap I was able to fix myself!

Having something that closely matches the REDCap API sounds sensible so there isn't a difficult learning curve. I'd look at similar python libraries and try to figure out best practice from those. It think it's quite usual to have a single client class and invoke the API from that. More recently I've been working with https://github.com/smart-on-fhir/client-py which has a client class (though confusingly also a server class that is accessed via the client).

**Comment by gammaflauge** [comment]
Plan looks solid to me 👍

The most similar project I've used is [PyGithub](https://github.com/PyGithub/PyGithub/tree/master/github).
Looks like they organize their classes just like you're proposing -- lots of bite-sized chunks that get combined in `MainClass.py` called `Github`.

**Comment by alexanderkgonzalez** [comment]
This is great work!

**Comment by pwildenhain** [comment]
>
>     1. I see how the two smaller classes (`RecordsAPI` & `MetadataAPI`) combine together to form the God class (`Project`).  Is this conventional in the Python world?
>

Yup as @gammaflauge pointed out, this is pretty common in the Python world
>
>     2. How would this help the developers grasp the complexity?  As a developer, it seems like now I have to learn & remember which functions are nested in which (super?)class.
>
Since we're dividing the code into the same logical groups that the REDCap docs themselves define, I think that would make it easier to say add a new endpoint as a first-time contributor 
>
>     3. What are the tradeoffs?
>
I think it's very hard to navigate a class that is over >2K lines long. The main benefit in my mind is the ease of use. I think this also quite nicely follows the single responsibility principle. It also gives users the option to use more lightweight classes in there are very performance oriented ⚡  
>
>     4. Any chance the categorization could be cosmetic?  Like our the function are categorized int he API playground, or how [pkgdown encourages categorizing](https://ouhscbbmc.github.io/REDCapR/reference/) functions/methods?
>
I'm willing that it is a purely cosmetic categorization -- I also think it's very useful though
>
>     5. In Python, can [the large class](https://github.com/redcap-tools/PyCap/blob/master/redcap/project.py) be split across different files?  (Like how R's functions can be defined in different files, then brought together as S3 methods in the class)?
>
I don't think you can, but I'm willingly to be proved wrong -- I think the way to of doing that is by creating different classes.


Thank you everyone for all the helpful feedback -- I'm going to tentatively continue in this direction, but feel free to leave other comments/critiques, and questions on this issue in the meantime
