### ISSUE TITLE
Decide on future on documentation

### ISSUE THREAD

**Issue by pwildenhain** [redcap-tools/PyCap#179]
First thing, the documentation will need to be updated regardless of what we decide here, so this issue also encompasses that

The future of the documentation really comes down to these factors:

- Do I feel like learning `.rst`?
- Are there good alternatives to using `.md` with `Sphinx`?
- Are there good alternatives to `Sphinx`?

**Comment by pwildenhain** [comment]
Some promising options

* `pycco`: https://realpython.com/generating-code-documentation-with-pycco/
* `lazydocs`: https://pythonrepo.com/repo/ml-tooling-lazydocs-python-documentation
* `mkdocs`: https://towardsdatascience.com/five-tips-for-automatic-python-documentation-7513825b760e

**Comment by remifrazierucsf** [comment]
@pwildenhain we could build up something in dexy.it as well - I'd love to help with that.

**Comment by pwildenhain** [comment]
@remifrazierucsf That would be great to have some help! I'm up for trying `dexy` (especially if that means you'll want to contribute!)

I took a look at the two "getting started" tutorials:
- https://www.mkdocs.org/getting-started/
- http://www.dexy.it/docs/getting-started.html

Seems like `dexy` has more support for running code within the documentation, which make it powerful but a little more complicated, while `mkdocs` is built for just simple markdown documentation, though seems like you need to compose multiple packages.

`dexy` also seems to be less popular, and less actively developed (the last push to `develop` was ~10 months ago, while `mkdocs` was updated 2 weeks ago though admittedly def doesn't mean the package is **not** actively developed).

Do you have examples of public sites that are documented with `dexy`? -- I know the `fastapi` tutorial is beautiful, and I would want to make sure `dexy` held up to that standard as well.

Again -- I'm up for `dexy` if that's what you prefer/want to contribute -- just want to cover all the bases.

**Comment by pwildenhain** [comment]
FYI @remifrazierucsf I'm taking the mkdocs route, but with it all just being straight markdown it should be super easy to jump in if you want! lmk if you have any issues 👍🏻
