### ISSUE TITLE
Unexpected Behavior: {Cannot export labeled headers by chunch}

### ISSUE THREAD

**Issue by Emma8a** [redcap-tools/PyCap#185]
I am exporting a large data by chunk. I cannot add the headers' label. Maybe json is not supported? When I export as one file csv, then raw_or_label_headers='label' gives me and error massage "NameError" . What am I doing wrong? Thank you.

**Comment by pwildenhain** [comment]
Can you post the code that won't run? That should help isolate the bug. Please ensure you don't post the project API

**Comment by Emma8a** [comment]
I used the following:
proj = redcap.Project(URL, TOKEN)

filter_4="[gender]= '1'" 
df_all = proj.export_records(export_data_access_groups= True,filter_logic=filter_4, format='csv',raw_or_label='label',raw_or_label_headers='label',export_checkbox_labels=True)

TypeError: export_records() got an unexpected keyword argument 'raw_or_label_headers'

**Comment by pwildenhain** [comment]
It seems like you misspelled one of the parameter names. Can you change raw_or_label_headers to just raw_or_label and see what happens?

**Comment by pwildenhain** [comment]
Seems like you're trying to use a parameter that doesn't exist. Try removing the raw_or_label_header parameter and the code should run

**Comment by Emma8a** [comment]
Yes, I have raw_or_label and headers also have labels, so in R or SAS it
calls as raw_or_label_headers='label' and raw_or_label='label'.

Thank you!

**Comment by pwildenhain** [comment]
Great, does that resolve this issue? If so, please close this out 👍🏻

**Comment by Emma8a** [comment]
No, it does not. It gives me an error message as the following:

TypeError: export_records() got an unexpected keyword argument
'raw_or_label_headers'

**Comment by pwildenhain** [comment]
Right, can you remove that regiment from the function call and see what happens? It seems that API option is not implemented for PyCap. If you would like that to be implemented, then I can change the issue title to reflect that

**Comment by Emma8a** [comment]
Yes, please --can you implement the option for extract_records with
filter_logic, raw_or_label, raw_or_label_headers, format, fields etc. in
addition to the supported options, please?
Most important options for the records_exports for us are:

   1. raw_or_label
   2. raw_or_label_heaaders
   3. filter_logic
   4. format
   5. export_checkbox_labels


Thank you so much,
Zula

**Comment by pwildenhain** [comment]
All of those other options exist for export_records except for raw_or_label_headers

**Comment by pwildenhain** [comment]
Also, if someone from your team wants to contribute this change, they can start a pull request and add it here: redcap/methods/records.py

Since it's just a Boolean parameter it should be relatively simple to add

**Comment by Emma8a** [comment]
We dont have any python developer. Thank you so much.

Could you notify me when you add the option? It is very urgently needed.

Thank you so much,

**Comment by pwildenhain** [comment]
Yup, you'll be notified when this issue is closed, which means the option has been added.

This package is community maintained, so I don't have any guarantees around when it will be implemented -- I'm about to have a newborn son, so my time for the next few weeks is going to be pretty packed 😁

**Comment by Emma8a** [comment]
Congratulations 🎊🎉🍾 

Thank you so much!

**Comment by Emma8a** [comment]
Just wanted to more clarification:
I am extracting by chunk the data. 
Most important options for the records_exports for us are:
raw_or_label=label
raw_or_label_heaaders =label
filter_logic=‘[man] =1 or [race]=2’ etc. a string list
format=csv
export_checkbox_labels=true

Thank you so much,
Zula

**Comment by pwildenhain** [comment]
This change is now on the master branch. You can install from github, and then try it out 😄 

Note: this new release does have some breaking changes in it, most notably that the `format` parameter in `export_records` has been changes to `format_type` (so `format="csv"` would become `format_type="csv"` in your case).

Excited to have a team test out the new and improved version before it goes live!

**Comment by Emma8a** [comment]
Thank you so much.
But still it does not working:

df_all = proj.export_records(export_data_access_groups=
True,raw_or_label_headers='label',filter_logic=filter_4,
format_type='csv',raw_or_label='label',export_checkbox_labels=True)


[image: image.png]


I was trying this batch mode and the same error:

def chunked_export (project, chunk_size=20):
    def chunks(l, n):
        for i in range (0, len(l), n):
            yield l[i:i+n]
    record_list =
project.export_records(fields=[project.def_field],raw_or_label_headers='true',
filter_logic=filter_4, raw_or_label='both',export_checkbox_labels='true')
    records = [r[project.def_field] for r in record_list]
    try:
        response = []
        for record_chunk in chunks(records, chunk_size):
            chunked_response =
project.export_records(records=record_chunk,raw_or_label_headers='true',filter_logic=filter_4,
raw_or_label='both',export_checkbox_labels='true')
            response.extend(chunked_response)
    except redcap.RedcapError:
        msg = "Chunked export failed for chunk_size={:d}".format(chunk_size)
        raise ValueError (msg)
    else:
        return response

**Comment by pwildenhain** [comment]
Your image didn't come through -- can you tell me what happens when you just try to run this line?

```py
proj.export_records(raw_or_label_headers='label', format_type='csv')
```
