### ISSUE TITLE
Unexpected Behavior: typing extensions not found

### ISSUE THREAD

**Issue by JuliaSprenger** [redcap-tools/PyCap#211]
When installing PyCap 2.0.0a0 with Python version 3.9 the `typing-extensions` module is missing. Maybe this is missing in the dependencies of the alpha release?

The issue occurred in the DigLabTools tests [here](https://github.com/INT-NIT/DigLabTools/runs/5583941915?check_suite_focus=true#step:7:53).

**Comment by pwildenhain** [comment]
Great find. This is currently defined as a dev dependency and should actually be defined as a core dependency. Are you interested in taking this? I can walk you through how to do this with poetry. If not I can provide a fix soon.

As a stop gap solution, you can always manually install typing-extensions in your environment along with PyCap

**Comment by pwildenhain** [comment]
@JuliaSprenger I've tested the new pre release version in a fresh virtual environment and everything seemed to work ok
