### ISSUE TITLE
API supporting form completion status

### ISSUE THREAD

**Issue by aboulang** [redcap-tools/PyCap#231]
Hi,

In the playground, I see the form completion variables as variables available to the metadata API but when executed the API returns an empty list. Are the completion variables unavailable by design or is this an API lapse? I need to have the completion status of the forms to build a dashboard of project data collection status. Here are 2 screenshots to help illustrate.

Best regards,
Albert Boulanger

![Screenshot 2022-04-12 143604](https://user-images.githubusercontent.com/5350313/163032115-fe474832-5dda-4711-808b-02aa26b2bdcf.png)
![Screenshot 2022-04-12 144325](https://user-images.githubusercontent.com/5350313/163032145-f55a594d-a114-4854-a5f4-09f12cbd0eb0.png)
r

**Comment by pwildenhain** [comment]
From what I remember, the auto-generated fields like the _complete fields are usually not included in the metadata. Same goes for fields like redcap_event_name, redcap_repeat_instance, etc. So I don't think this is a bug

Now if you wanted to limit to those fields in export_records, then it should work.

To be clear, I'm not formally affiliated with REDCap. So if you think something like this _should_ be supported I suggest you get in touch with the REDCap admins at your site

**Comment by pwildenhain** [comment]
Great points -- if they're in the data dictionary then then should definitely be included in the metadata export. Sounds like an API bug. I would reach out to your REDCap admins who can raise the issue with the REDCap development team at Vanderbilt 

Best of luck
