### ISSUE TITLE
2.10 version changes report methods

### ISSUE THREAD

**Issue by jthomas08** [redcap-tools/PyCap#233]
Team,
Tried to run a pre-2.1 code base on the most recent pycap and it looks like the method to export reports changes from Project. export_reports to export_report (singular). Is that right?

**Comment by pwildenhain** [comment]
That is correct -- though I think you mean version 2.1 -- hopefully 2.10 doesn't come out for a while!

We changed this for the 2.0 release because the API changed by only allowing one report to be exported at a time

**Comment by pwildenhain** [comment]
Ah whoops -- I meant to clarify this his changed in the 2.0 release (which had a few breaking changes), not the 2.1 release

**Comment by jthomas08** [comment]
Got it..thnx
