### ISSUE TITLE
Unexpected Behavior: calculated fields not updating

### ISSUE THREAD

**Issue by alex-silverman** [redcap-tools/PyCap#271]
**Problem summary**: There are a few fields in my redcap project that are calculated fields. When I run a python script to `import_records()` into the project, these calculated fields are only sometimes getting filled out. (Technically, the fields are Text Boxes in redcap, but with a `@CALCTEXT()` Action Tag.)

**Example where it DOESN'T work:**
Here's the Action Tag/Field Annotation for one such calculated field that does not automatically calculate, l_unit6:

`@HIDDEN @CALCTEXT(
    if([l_fac_bu] = '2' and [l_bu_unit2(6)] = '1', 'Test 1', 
        if([l_fac_bu] = '4' and [l_bu_unit4(6)] = '1','Test 2','' )
    )
)
`

My code successfully updates [l_fac_bu] to '4' and [l_bu_unit4(6)] (a.k.a. l_bu_unit4___6) to '1'. However, l_unit6 remains empty, instead of being "Test 2". I know it's empty by running `export_records()` immediately after creating the record.

**Example where it DOES work:**
The Action Tag/Field Annotation for l_unit4 is:

`@HIDDEN @CALCTEXT(
    if([l_fac_bu] = '1' and [l_bu_unit1(4)] = '1', 'Test 1', 
        if([l_fac_bu] = '2' and [l_bu_unit2(4)] = '1', 'Test 2', 
            if([l_fac_bu] = '3' and [l_bu_unit3(4)] = '1', 'Test 3', 
                if([l_fac_bu] = '4' and [l_bu_unit4(4)] = '1', 'Test 4', 
                    if([l_fac_bu] = '5' and [l_bu_unit5(4)] = '1', 'Test 5','')
                )
            )
         )
    )
)
`

My code successfully updates [l_fac_bu] to '5' and [l_bu_unit5(4)] (a.k.a. l_bu_unit5___4) to '1'. And l_unit4 is also successfully set to "Test 5".

**Additional context**: 

- Virtually everything else about the two scenarios is the same, including data access group, field types, form, etc.
- Additionally, if I simply open and save the form that the underlying (non-calculated) fields are on, the calculated field is triggered.
- A suitable workaround would be the ability to trigger a form save, which will trigger the calculated field.

**Expected behavior**: Since it works sometimes, I would expect the calculated field to *always* be filled in when it meets any of the underlying criteria.

**Desktop:**
 - OS: Windows 10
 - REDCap version 13.8.2
 - PyCap Version 2.4.0

**Comment by pwildenhain** [comment]
Is there a reason you closed this? Just want to check before we dig too much into it

**Comment by alex-silverman** [comment]
Two reasons: 1) I wasn't able to prepare a reprex, and 2) I think it's
probably an issue with redcap, not pycap. The uploaded data goes in as
expected; it's just that the calculated fields (which are technically
@HIDDEN and @CALCTEXT textboxes) don't necessarily update. If I simply save
the form in redcap, then they do. So I do wish pycap had a way to trigger a
form save.

**Comment by pwildenhain** [comment]
Yea that was my initial thought as well -- the API doesn't seem to place nice with the calculated fields, specifically @CALCTEXT, when importing data.

An easy to way to update them all is actually to go to the "Data Quality Rules" section of the project, which you should see in the left hand sidebar. You might need to enable it in the user rights if you don't see it 

Once there you can run the rule related to calculated fields, and it should have an option to automatically fix all calculated fields
