### ISSUE TITLE
Interested in command-line tools / "minimum change" update algorithm?

### ISSUE THREAD

**Issue by njvack** [redcap-tools/PyCap#286]
Hey there,

Over the years, we've built a few things on top of PyCap, and I'm wondering if you'd be interested in having them as pull requests. We've got:

- A command-line tool that just downloads all the REDCap data for a project and saves it to a CSV file
- A tool that splits the data into separate files per-event and per-repeated-instrument (essentially: ensures you have one row per record_id)
- An algorithm and command-line tool that updates a project with only the changes between two dataframes / CSV files

If you're interested, we can make PRs; if that's not stuff you'd like to be part of PyCap, that would totally make sense and we can make a separate package that depends on you.

Thanks!

**Comment by pwildenhain** [comment]
I think it would be best to keep the tools separate -- I've done similar work where I've built existing packages to help with data management on top of `PyCap` and that's worked out well for me so far.

These tools sound really cool -- have you thought about presenting them at the upcoming [REDCapCon](https://projectredcap.org/about/redcapcon/)?

**Comment by njvack** [comment]
Oh! I thought I'd responded to this, but I guess not. I think we actually aren't eligible to attend REDCapCon; we aren't actually site admins, just very enthusiastic users who support other end-users. I am not, generally, a big fan of the administrator / end-user split in REDCap's governance, but hey, I don't make the rules.

For now we'll plan to release the tools into our own organization. Longer-term, do you think it might be appropriate to put the main repo in the redcap-tools organization? We plan to continue using REDCap and maintaining tools for the foreseeable future; in the long term, though, having governance beyond a random group of devs in Madison might be nice.
