### ISSUE TITLE
flagged as spam on ReadTheDocs

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/PyCap#290]
I noticed this was flagged when I checked my R package.  (So I can pass CRAN, I'll probably reference <https://pypi.org/project/pycap/>.)

![image](https://github.com/user-attachments/assets/74c20209-ab21-4d9a-a1fd-15650a22da37)

```
410 Project unavailable
[pycap.readthedocs.io](https://pycap.readthedocs.io/)
This project was flagged as spam and is currently disabled.

Please [contact us](https://pycap.readthedocs.io/en/latest/) if you think this is a mistake.
```

**Comment by pwildenhain** [comment]
Yup, and I do have a documentation site on
http://redcap-tools.github.io/PyCap/
 if you want to link that instead

Paul Wildenhain
