### ISSUE TITLE
New Survey Methods

### ISSUE THREAD

**Issue by sburns** [redcap-tools/PyCap#47]
Redcap has added new methods, we need to keep up (I've included screenshots of the documentation for each)
-   Export PDF file of Data Collection Instruments
  ![](https://www.evernote.com/shard/s132/sh/cc5b8e43-53ec-470a-8317-3cee682212cc/1f9a36560c39a2b15dd7b795f4d6e1d3/deep/0/REDCap.png)
-   Export a Survey Link for a Participant
  ![](https://www.evernote.com/shard/s132/sh/8be57d6f-2b34-4944-9a16-142b990eb6ea/fabba53956ccaeeee58931e2329b45a0/deep/0/REDCap.png)
-   Export a Survey Queue Link for a Participant
  ![](https://www.evernote.com/shard/s132/sh/73be6ea9-a8fb-49ff-9d8e-a335a707a2fa/56d5e3dabcca4c95544752e32cc46198/deep/0/REDCap.png)
-   Export a Survey Return Code for a Participant
  ![](https://www.evernote.com/shard/s132/sh/a715024d-dadf-42c4-9cfa-73f89e9a0b03/3e5cdedb0eea02d1e5304ea38ccf17ba/deep/0/REDCap.png)
-   Export a Survey Participant List
  ![](https://www.evernote.com/shard/s132/sh/6ffe049c-483a-46fe-88ae-ee9dba3fe34b/b3a99cf814fab3cba4d1e2c06b5edefd/deep/0/REDCap.png)
-   Export List of Export Field Names
  ![](https://www.evernote.com/shard/s132/sh/f7a9692c-69a7-4497-82ca-ac589b56583f/9a5ea5e948b36a847d81a1685739a721/deep/0/REDCap.png)

**Comment by sburns** [comment]
@dgutman here's your issue, want to take a crack at it? You don't have to do all, we might split this issue up if it helps...

**Comment by pwildenhain** [comment]
Good to know that these are here, I'm going to close this issue, and just reopen/refer back if someone requests this functionality
