### ISSUE TITLE
Saving all records in place

### ISSUE THREAD

**Issue by mateolan** [redcap-tools/PyCap#49]
Hi Scott et al,

Thanks for your great work on PyCap. 

I am using it to pull subjects from a couple different trial arms into an external DB, and it is working flawlessly and saving us tons of labor hours. However, now I need my automated surveys within Redcap to send out 90 days after one specific form has been completed. I have the calculation inside my RedCap 'Automated Invitations', but it only tests the automation logic on a record save action. I don't want to mess with importing recs into RedCap or anything like that, I just want to save all the records at once, as they are in place, everyday (cron job of course), in order trigger the form to be sent for appropriate records. I just know I must be missing something simple (probably really simple), but I just don't see it in the PyCap API or documentation...but I would have to imagine that this is a much desired functionality since clearly it's a design flaw in RedCap itself.

Your help is very much appreciated. If you point me in the right direction, I will gladly contribute to documentation to make it better.

Best,

~mc

**Comment by sburns** [comment]
Hi Matthew, 

You'll have to forgive me, I haven't dealt with automated surveys before. To send the automated invitations, does the Redcap server look at a particular field (per chance a text field that is validated to be a date?) and if today is that date, it sends them? If so, here's the script I'd write:

* Export all records along w/ the status of the survey name which is something like `[survey_name]_complete`.
* Filter your records for where `[survey_name]_complete` == 2. This tells you who has completed the specific form.
* For these records, build a list of dictionaries looking like `[{project.def_field: id1, automated_date_field: DATE_90_DAYS_FROM_NOW},...]`.
* Import this list. This will update only the records that have completed the survey.

I have no idea whether this import will trigger Redcap on the backend to send invitations but at least the pertinent records will have the correct dates in the triggered field. If it doesn't, you may need to interact with the web app and save one of the records to trigger it.

I hope this helps and please correct me if I'm not thinking about it correctly.

Scott
