### ISSUE TITLE
TypeError creating classic project after upgrade to REDCap 6.4.4

### ISSUE THREAD

**Issue by dckc** [redcap-tools/PyCap#54]
my call to Project() used to work, but we recently upgraded to REDCap 6.4.4 and now I get:

```
  File ".../python2.6/site-packages/redcap/project.py", line 52, in __init__
    arm_nums = tuple([a['arm_num'] for a in arm_data])
TypeError: string indices must be integers
```

a debug session shows that for class projects, the REDCap API succeeds where the code expects an error; then the code goes to get the arm info and the REDCap API says "no, silly!"

```
.../python2.6/site-packages/redcap/project.py(46)__init__()
-> if 'error' in ev_data:
(Pdb) p ev_data
[{u'day_offset': u'0', u'event_name': u'Event 1', u'arm_num': u'1', u'offset_min': u'0', u'unique_event_name': u'event_1_arm_1', u'offset_max': u'0'}]
(Pdb) n
> .../python2.6/site-packages/redcap/project.py(51)__init__()
-> events = ev_data
(Pdb) n
> .../python2.6/site-packages/redcap/project.py(52)__init__()
-> arm_data = self._call_api(self.__basepl('arm'), 'exp_arm')[0]
(Pdb) n
> .../python2.6/site-packages/redcap/project.py(53)__init__()
-> arm_nums = tuple([a['arm_num'] for a in arm_data])
(Pdb) p arm_data
{u'error': u'You cannot export arms for classic projects'}
```

obligatory version info:

```
> pip freeze | grep PyCap
PyCap==1.0
```

**Comment by dckc** [comment]
turns out my project *was* longitudinal, but it had no events. Disabling longitudinal worked around the problem.

still, the crash isn't nice.

**Comment by sburns** [comment]
The whole reason I asked a *long* time ago to version their API :(

**Comment by bruth** [comment]
I observed the same behavior.

**Comment by pwildenhain** [comment]
Since this seems to have somewhat of a solutions, now that the version is available, I'll close this out. Feel free to reopen if necessary
