### ISSUE TITLE
Add support for REDCap version API

### ISSUE THREAD

**Issue by pbchase** [redcap-tools/PyCap#57]
Scott, in Issue #54, you lament there is no API version.  What of the Export REDCap Version API?  Would this be helpful if we implemented it? It's not an API version number, but it might help PyCap determine the appropriate response.
# Export REDCap Version
## Description

This method returns the current REDCap version number as plain text (e.g., 4.13.18, 5.12.2, 6.0.0).
## URL

https://host.domain/redcap/api/
## Supported Request Methods

POST
## Parameters (case sensitive)

Required
- token
  the API token specific to your REDCap project and username (each token is unique to each user for each project) - See the section above for obtaining a token for a given project
- content
  version
## Returns:

the current REDCap version number (three numbers delimited with two periods) as plain text - e.g., 4.13.18, 5.12.2, 6.0.0

**Comment by tjrivera** [comment]
Hi @pbchase. Would the functionality introduced here: https://github.com/sburns/PyCap/pull/44 meet your needs?

**Comment by sburns** [comment]
Do we know if that API call was back ported to previous versions?

**Comment by pbchase** [comment]
I spoke with Rob about REDCap version API.  He says it was *not* back ported.  

Sorry about not noticing the the code that resolved Issue #44.

**Comment by pwildenhain** [comment]
Since it seems like this issue has been resolved, I'll close it for now. Feel free to reopen if necessary
