### ISSUE TITLE
Organization Change

### ISSUE THREAD

**Issue by sburns** [redcap-tools/PyCap#58]
Hey everyone, after having a great discussion with @pbchase, I've decided to move PyCap to a new organization. I'd like it to be a place where people can put interesting projects based against REDCap. I actually don't want it to be python focused ( :smile:  @wibeasley) but rather language agnostic. 

Obviously some projects have certain ownership that must be maintained, either at the laboratory or university level. I'm not asking for private code but rather fun projects that have either scratched an itch or you depend on day in and day out that should be shepherded by a group of like-minded individuals.

I just need a name! Thoughts?

I will definitely put everyone who has contributed either in code or otherwise.

@dckc @aaron0browne @tjrivera @nicholsn @bud42 @byvernault 

## To do list

- [ ] New ReadTheDocs project
- [ ] Update TravisCI (since github forwards org changes maybe that'll just work?)

**Comment by sburns** [comment]
@dgutman

**Comment by wibeasley** [comment]
(*I think @pbchase's group has figured out some great things (related to Travis and to Epic), and I was happy a few days ago at the conference when Philip mentioned the possibility his group would get involved with the API and PyCap.*)

My first reaction to a GitHub organization name would be something like 'REDCapProgramming'.  If the organization did assume a general name, I think it should have a casual responsibility to reference other REDCap-related projects that are in other organizations (eg, @aarenson's [PhpCap](https://github.com/aarenson/PhpCap)).  If you need something to seed that list, feel free to copy the list from REDCapR's [readme](https://github.com/OuhscBbmc/REDCapR).

----------

As a separate issue, we have an official REDCap Consortium committee dedicated to this kind of thing (our name is anything but concise  -something 'REDCap Plug-ins/Hooks/API Committee').  We haven't met as a group in a while, but I think we talk in pairs a lot.

It may make sense to have that committee affiliated with this new GitHub organization.  It would contain  *public* repos that anyone could get involved with (regardless if they're a member of the  committee or even of the consortium).  Although the org was associated with the committee, I imagine its repos should disclaim that their not officially connected to Vandy or the responsibility of REDCap developers.  I think that was our intention with [redcap-extras](https://github.com/susom/redcap-extras) which was intended for hooks & plugins.  But I think there's some thing that could deserve an isolated repo.

@sburns, we'd be happy for you to be one of the 'owners' of the GitHub organization (and I think I've previously invited you and @nutterb to the committee too).  I'm an admin/owner for ~3 GitHub organizations, and it requires a few hours every month assigning people to groups, and occasionally creating repos for them.  If the GitHub organization is affiliated with the Consortium Committee, you'll be able to hand it off to someone in the future if something changes with your job where you don't have as much time/motivation to dedicate to overseeing the organization's repos.

(cc others who've contributed to REDCap-related repos: @haozhu233 @rparrish @nutterb @123andy)

**Comment by dgutman** [comment]
Sounds great to me...

**Comment by tjrivera** [comment]
I'd certainly like to be involved. Also throwing my golang redcap client into the mix: https://github.com/tjrivera/go-cap

**Comment by aarenson** [comment]
Sounds very good. I'm happy to move PHPCap to a general REDCap organization.

**Comment by nicholsn** [comment]
+1 sounds great to me too!

**Comment by dgutman** [comment]
Agreed---  Has anyone updated the API to pull the URL for a redcap survey?
I was going to have to start working on that in the near(ish) future..

dg
