### ISSUE TITLE
Can no longer access form _complete variables

### ISSUE THREAD

**Issue by bloyl** [redcap-tools/PyCap#74]
In the past I was able to access the form status from a full redcap export. now that field is only available if i only pull that form specifically.

for example if i have a form called test

`export_records(forms=['test'])`
will result in rows with the variable 'test_complete' in them
however
`export_records()`
will not.

Is this intended behaviour?

**Comment by sburns** [comment]
I believe this is an upstream change in the API behavior, not PyCap persay.

**Comment by pwildenhain** [comment]
Specifying all of those forms of the project worked for me -- a little tedious and unexpected, but not killer

**Comment by sburns** [comment]
I'm glad it works, still seems like an API change on REDCaps side though.

**Comment by pwildenhain** [comment]
Is this something that can be addressed in the [`backfill_fields()`](https://github.com/redcap-tools/PyCap/blob/master/redcap/project.py#L354) method? If the change is relatively simple, I'm open to submitting a PR

**Comment by pwildenhain** [comment]
With #125 you can now get all the fields from project, and then use that in the `fields` parameter of `Project.export_records()` to get the `_complete` fields. This, in addition to the workaround mentioned above, should be sufficient.
