### ISSUE TITLE
Cant find examples for using filter()

### ISSUE THREAD

**Issue by tomwright01** [redcap-tools/PyCap#75]
Hi,
Thanks for this work. Is there any examples for using the filter() function?

I can't determine what the expected object `query` is. Also do you know of any more documentation about the filterlogic strings expected by redcap are?

Thanks.

**Comment by sburns** [comment]
Sorry I wouldn't depend on that at all. I started going down that route until I found pandas. I wouldn't depend on PyCap to filter API responses. I would 100% recommend exporting the records into pandas DataFrame  (`project.export_records(...format='df')` and doing filtering from there.

If pandas is too onerous to install, I'd use some combination of list comprehensions or the built-in `filter` to extract records of interest.

**Comment by tomwright01** [comment]
OK, fair answer. I already started with the list comprehension route while I waited for your answer.
