### ISSUE TITLE
export records pagination? LIMIT / OFFSET?

### ISSUE THREAD

**Issue by dckc** [redcap-tools/PyCap#80]
We've got a project with >10K records. When we try to export just the record_id field from this project, we get:
> REDCap ran out of server memory. The request cannot be processed. Please try importing/exporting a smaller amount of data.

I see a `filter` parameter when exporting records, but I'm struggling to figure out how to use that for pagination in a general-purpose way.

Suggestions?

**Comment by sburns** [comment]
There’s a section in the [export docs](http://pycap.readthedocs.io/en/latest/deep.html#exporting-data) about hacking this on the client side. If the API has added better functionality around this then PyCap could theoretically take advantage of it. 

Hope this helps!

**Comment by dckc** [comment]
Yes, we're using exactly that technique. The failure is, as I say, when we try to export just the record_id field:

```
...
    record_list = project.export_records(fields=[project.def_field])
...
```

On the other hand, it seems to be a transient issue. I'm having trouble reproducing it.

**Comment by pwildenhain** [comment]
I've exported projects with over >10K records with no issue on recent versions on REDCap/`PyCap`. If this issues persists, and you think it can be solved on the `PyCap` side, then we can revist. Closing for now.
