### ISSUE TITLE
import_file does not work in REDCap 7.4.23

### ISSUE THREAD

**Issue by mkaut** [redcap-tools/PyCap#81]
I cannot make the `file_import` to work, working with a server running REDCap 7.4.23.
I followed the example from [http://pycap.readthedocs.io/en/latest/deep.html#working-with-files](url), but it fails with `HTTPError: 400 Client Error: Bad Request for url`.
Interestingly, it fails also from REDCap's API playground, but I managed to import the file using curl from the command line (in linux).

I have just started with REDCap, so I do not know how this worked on earlier versions

I have also noticed that the REDCap documentation for the import API does not have a parameter for file name (and, indeed, it gets ignored when using curl), but has an additional parameter `repeat_instance`, needed to upload a file to repeating instruments.

**Comment by sburns** [comment]
Can you send the full successful HTTP request curl makes when uploading a file?

**Comment by sburns** [comment]
Also it would be helpful to raise an issue with REDCap that their API Playground fails to import files. @firaswehbe are you still apart of the mailing list/have any pull there  :)?

**Comment by mkaut** [comment]
Here is the command that works for me - adopted from the auto-generated code in the API Playground.
```
curl -H "Accept: application/json" \
     -F "token=MY_TOKEN" \
     -F "content=file" \
     -F "action=import" \
     -F "record=30" \
     -F "field=result_image" \
     -F "repeat_instance=2" \
     -F "file=@/path/to/image.png" \
     https://redcap.helsenord.no/redcap/api/
```
The `repeat_instance` makes sense only for repeat instruments; if omitted, it defaults to 1. This is **not** available in the API Playground, but is mentioned in the documentation.
The auto-generated curl code includes also a `filename` field, even if it does not exist in the input and does not figure in the auto-generated code for the other languages .. and is **not** mentioned in the documentation of the import method.
For longitudinal projects, there is the `event` field in addition.

As for raising an issue with REDCap - where do I do this?

**Comment by remifrazierucsf** [comment]
Scott – the issue has to be raised by a sysad from one of the sites who is also a member of the central consortium.  If we can put together a clear problem statement, we can submit it from UCSF.

___ _ ____ _ _____ _________ __ ______
Remi Frazier
remi.frazier@ucsf.edu<mailto:remi.frazier@ucsf.edu>
Data Scientist/Systems Architect
UCSF Center for AIDS Prevention Studies
550 16th Street, Suite 3153
San Francisco, CA 94143
415.502.1000 ext. 66270 (vm only) <-- new number

**Comment by mkaut** [comment]
I am afraid I have no idea about such things. We were just given access 
to a REDCap instance running at a different institution, just for doing 
one specific project.

**Comment by sburns** [comment]
If you can make it work with cURL, can you try to make it work directly with the python requests library. PyCap is really just a fancy wrapper around that. That'd give us some clue into why uploading files via PyCap isn't working.

**Comment by bobromeo** [comment]
I cannot get import_file to work, but foloowing works:
<pre>
dataFile = {'token': api_key, 'content': 'file', 'action': 'import', 'record': 'R_E_C_O_R_D', 'field': 'file', 'returnFormat': 'csv'
}
file = {'file':(open("Records.csv","r"))}
rf = requests.post(api_url, data=dataFile, files=file, verify=False)
print(str(rf))
</pre>

**Comment by remifrazierucsf** [comment]
Bob – we need more information about what happens when import_file fails.

**Comment by sburns** [comment]
I'm noticing the `verify=False` arg in your POST request. If you create a project with `Project(URL, TOKEN, verify_ssl=False)` does the file import work?

**Comment by bobromeo** [comment]
I already had the following statement:
``project = Project(api_url,api_key,verify_ssl=False,lazy=True)``
I'll try some more on 'import_file'.

**Comment by bobromeo** [comment]
Program ghrc01.py with output: Error: line 616 in _check_file_field
is_field = field in self.fieldnames ==> ``TypeError: argument of type 'NoneType' is not iterable``
<pre>
#ghrc01 - GitHubRedCap
#WinServer2012/Anaconda3/Python 3.7.3/pip PyCap 0.0.0/REDCap 8.10.7/
import requests
from redcap import Project

api_url = 'https://www.example/redcap/api/'
api_key = '********'
project = Project(api_url,api_key,verify_ssl=False,lazy=True)
print('-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*')
dataFile = {'token': api_key, 'content': 'file', 'action': 'import', 'record': 'FLOG', 'field': 'file', 'returnFormat': 'csv'
}
file = {'file':(open("test.txt","r"))}
rf = requests.post(api_url, data=dataFile, files=file, verify=False)
print(str(rf))
print('-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*')
record  = 'FLOG'
field   = 'file'
fname   = 'test.txt'
#fobj    = open(fname)  #Must iterate ?!?
with open(fname,'r') as fobj:
    project.import_file(record,field,fname,fobj)

#print(rf)
print('-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*')
</pre>
Output:
<pre>
H:\py>python -W ignore ghrc01.py
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Response [200]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Traceback (most recent call last):
  File "ghrc01.py", line 22, in <module>
    project.import_file(record,field,fname,fobj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\redcap\project.py", line 564,
 in import_file
    self._check_file_field(field)
  File "C:\ProgramData\Anaconda3\lib\site-packages\redcap\project.py", line 616,
 in _check_file_field
    is_field = field in self.field_names
TypeError: argument of type 'NoneType' is not iterable
</pre>

**Comment by sburns** [comment]
Field names aren't loaded because of `lazy=True` in the constructor. Can you remove that and try again?

**Comment by bobromeo** [comment]
Will do. But now we have trouble with ~event-logs~, waiting on the administrator.

**Comment by bobromeo** [comment]
***WARNING*** BUG in REDCap 8.10.7: When deleting records via the API, associated uploaded files are *not* deleted. (Not yet tested with the web UI)
