### ISSUE TITLE
Dealing with large export - issue with chunked_export()

### ISSUE THREAD

**Issue by sufkes** [redcap-tools/PyCap#84]
In the Read the Docs documentation, a function is provided which performs chunked records export (see http://pycap.readthedocs.io/en/latest/deep.html#exporting-data). This functionality is very important at least for our project.

For longitudinal projects with many events, the chucked_export() function will pull records in duplicate if a certain record ID lies in rows (multiple rows for multiple events) which cross the edge of a chunk. 

E.g. chunk_size = 500 
500th row: "record_id_234"     <- row for "event 1"
501st row: "record_id_234"     <- row for "event 2" 

In such cases, all rows for "record_id_234" will be pull in the first and second chunk, duplicating the rows.

**Comment by sburns** [comment]
I'd be more than welcome to merge a pull-request with an updated chunk function for the docs, but this is not a high priority right now. This is an example function in the docs and doesn't ship as part of PyCap proper. It sounds like you've found a fix for yourselves, its hard to say how many other groups have had to deal with subjects crossing chunk boundaries.

**Comment by sufkes** [comment]
Thanks. I just wanted to comment somewhere in case other people have this problem. I would argue that if a project has multiple events and requires chunked record export, it is very likely that the subjects will cross the chunk boundaries.

**Comment by sburns** [comment]
Thank you! I'm glad it continues to be useful even as I've mostly moved on.
