### ISSUE TITLE
Version is set to 0.0.0 after installing with pip

### ISSUE THREAD

**Issue by jjv5** [redcap-tools/PyCap#87]
`./pip install -e git+https://github.com/sburns/PyCap.git#egg=PyCap`

$ ./pip show pycap
Name: PyCap
Version: 0.0.0
Summary: PyCap: Python interface to REDCap
Home-page: http://sburns.github.com/PyCap
Author: None
Author-email: None
License: MIT
Location: /programs/x86_64-linux/python/3.6.5/bin/src/pycap
Requires: requests, semantic-version
Required-by:

**Comment by nathanbegbie** [comment]
Hi there 👋

I'm just following up on this - if I run pip install pycap>=1.0.2 or pip install pycap, which should give me the latest version of PyCap.

I then run the following:

» pip freeze | grep PyCap
PyCap==0.0.0

I would expect that it would read 1.0.2 or greater. I'm not very familiar with python packaging processes, but happy to help with how one might update this . . .

I understand that this is not actively being maintained though, but any help is appreciated (and thanks for the helpful package)!

**Comment by sburns** [comment]
I guess this'll really matter if someone tries to put PyCap in a requirements.txt or install_requires of setup.py
