### ISSUE TITLE
export individual events?

### ISSUE THREAD

**Issue by ndharper** [redcap-tools/PyCap#88]
Hi There,

I suspect I'm asking about something that's a feature not a bug.  When do an export and specify the records and the events but don't specify what fields I get an export with all fields from all events for the specified records.  The field value returned is null if that field is in an event that I didn't ask for.

Is this the way it's supposed to work or have I missed something? 

Regards
Nick

events_of_interest = ['fetal_scan_arm_1', 'neonatal_scan_arm_1','baby_born_arm_1']
data = project.export_records(records=records_of_interest,events=events_of_interest,format='json')

**Comment by sburns** [comment]
Yeah this is just how the REDCap API works, it's going to include all fields if none were specified. Nothing special PyCap is doing, it's just passing along unhelpful information :)
