### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by datagarret** [redcap-tools/PyCap#89]
Can you update the version that is on pypi? Some of the functionality is missing that is on available on the github. For example export_records is missing filter_logic.

**Comment by firaswehbe** [comment]
Did you try installing directly from github? Something like this

```bash
pip install git+https://github.com/redcap-tools/PyCap.git
 ```

**Comment by sburns** [comment]
That works too...I'll see if I can cut a release but it'll probably be next week or so.

**Comment by datagarret** [comment]
Thanks @firaswehbe

@sburns much appreciated.

**Comment by nathanbegbie** [comment]
Hi there 👋 

I'm just following up on this - if I run `pip install pycap>=1.0.2` or `pip install pycap`, which should give me the latest version of PyCap.

I then run the following:
```
» pip freeze | grep PyCap
PyCap==0.0.0
```
I would expect that it would read `1.0.2` or greater. I'm not very familiar with python packaging processes, but happy to help with how one might update this . . .

I understand that this is not actively being maintained though, but any help is appreciated (and thanks for the helpful package)!

**Comment by pwildenhain** [comment]
Is this still on the to-do list? I also tried to use `filter_logic` but got an error
```
TypeError: export_records() got an unexpected keyword argument 'filter_logic'
```

**Comment by sburns** [comment]
```
patient: hi doc, it hurts when i do this.
dr: then don't do that.
```

In all seriousness, this will likely be better fixed in #109 with a new set of stewards for the project.

**Comment by pwildenhain** [comment]
Once we can merge/close a few more of the outstanding PRs, we can arrange another release to PyPi

**Comment by pwildenhain** [comment]
🎉 Released to pypi 1️⃣ . 1️⃣ . 0️⃣
