### ISSUE TITLE
Adding method for Exporting Reports

### ISSUE THREAD

**Issue by mcarmack** [redcap-tools/PyCap#90]
I am looking to use the exportReport function of the Redcap API. Are there any plans to make a pyCap wrapper for that? 

I am somewhat new to pyCap, and the Redcap API, so I haven't tried adding to pycap yet. 

If this is not likely to be added, another method that would be useful would be a wrapper for newer (and unsupported) Redcap API functions (such as exportReport, export survey participant link, etc).

Really appreciate any guidance or updates on this!

**Comment by bobromeo** [comment]
Maybe this helps, using requests.
<pre>
import requests
api_url = 'https://example.com/redcap/api/'
api_key = 'AddingmethodforExportingReports'
dataRep = {
    'token': api_key,
    'content': 'report',
    'format': 'csv',
    'report_id': '9',
    'rawOrLabel': 'raw',
    'rawOrLabelHeaders': 'raw',
    'exportCheckboxLabel': 'false',
    'returnFormat': 'json'
}
r = requests.post(api_url, data = dataRep, verify=False)
print(r.text)
</pre>
