### ISSUE TITLE
Docs hooked up correctly?

### ISSUE THREAD

**Issue by jmillxyz** [redcap-tools/PyCap#93]
I noticed after my last PR that a few portions of the docs _should_ have changed, but didn't seem to. 

For example: in [backfill_fields()](https://pycap.readthedocs.io/en/latest/api.html#redcap.project.Project.backfill_fields) I would have expected the `Returns` portion to now be aligned under `Parameters`, but it doesn't seem as though it is. 

I'm not familiar with the way this project deploys to readthedocs, is there something we need to do in order to keep the docs current?

(On a side note I also realized we should probably only be deploying them once, not for each version of python)

**Comment by sburns** [comment]
1. Set up a new webhook to deliver push/tag creation/tag deletion events to RtD
2. Make a new build
3. I see https://pycap.readthedocs.io/en/latest/api.html#redcap.project.Project.backfill_fields now 🎉

**Comment by jmillxyz** [comment]
Thanks!
