### ISSUE TITLE
help in import data (csv file) into redcap

### ISSUE THREAD

**Issue by vinotharyan** [redcap-tools/PyCap#96]
The problem I am trying to solve is I have CSV files which contain the patient's record like record_id, age, sex....etc and all personal details.

I need to import those data in particular form (" Pre-screening form" ) in redcap I am not able to manually import the data because it contains more 1 million, patients records for that reason I need to use python or R by API in redcap.

 so used the below code

fname = 'Redcap_data.csv' 
 with open(fname, 'r') as fobj:
        proj.import_file('1','record_id', fname, fobj) 

but it not working for my problem. I am getting an error  
ValueError: 'record_id' is not a field or not a 'file' fie

Can you help me solve my problem? or share any resource relevant to this problem.

**Comment by vinotharyan** [comment]
I Try this code to 

import csv

with open('my_file.csv') as fobj:
    reader = csv.DictReader(fobj)  # DictReader will take the first row as the header
    data = [row for row in reader]

proj.import_records(data)

I Am getting this error 
---------------------------------------------------------------------------
RequestException                          Traceback (most recent call last)
<ipython-input-5-9ca0d92d3b58> in <module>()
      5     data = [row for row in reader]
      6 
----> 7 proj.import_records(data)

C:\ProgramData\Anaconda3\lib\site-packages\redcap\project.py in import_records(self, to_import, overwrite, format, return_format, return_content, date_format)
    485         response = self._call_api(pl, 'imp_record')[0]
    486         if 'error' in response:
--> 487             raise RedcapError(str(response))
    488         return response
    489 
RequestException: {'error': '"101","last_name","deliatest","This field (\'last_name\') exists on an instrument that is not designated for the event named \'Screening (Arm 1: Screening)\'. You are not allowed to import data for this field into this event."\n"101","first_name","deliatest","This field (\'first_name\') exists on an instrument that is not designated for the event named \'Screening (Arm 1: Screening)\'. You are not allowed to import data for this field into this event."\n"101","age","1","This field (\'age\') exists on an instrument that is not designated for the event named \'Screening (Arm 1: Screening)\'. You are not allowed to import data for this field into this event."\n"107","last_name","Gani","This field (\'last_name\') exists on an instrument that is not designated for the event named \'Screening (Arm 1: Screening)\'.

**Comment by vinotharyan** [comment]
import csv

with open('mydata.csv') as fobj:
    reader = csv.DictReader(fobj)  # DictReader will take the first row as the header
    data = [row for row in reader]

proj.import_records(data)

Its work i am able to import data 

but i am able to import only 1000 records at time but I have 1 million records to import I did not know how to do that. and also i import data into only one form it's possible or not.

**Comment by sburns** [comment]
Hi @vinotharyan, I would try something like this...


```python

import csv

with open('mydata.csv') as fobj
    reader = csv.DictReader(fobj)
    data = [row for row in reader]

# data is now 1M dicts?
chunk = []
imported = 0
chunk_size = 1000
for record in data:
    chunk.append(record)
    if len(chunk) == chunk_size:
        # import this chunk of records
        proj.import_records(chunk)
        # reset the chunk
        chunk = []
        imported += chunk_size
        print("Imported {} records".format(imported))
# make sure to get the remainder
proj.import_records(chunk)
```

**Comment by vinotharyan** [comment]
@sburns Thank you so much for your help

I want to import data only in one form in redcap is that possible
