### ISSUE TITLE
how to import/Programmatic change  or add Survey Invitation Log( time to send the call to participants)

### ISSUE THREAD

**Issue by vinotharyan** [redcap-tools/PyCap#98]
Hello Everyone,

In my project, we are sending a call to each participant by every week to follow how they're doing the exercise through IVR system( which voice call) its becoming hard to schedule the call each participants for whole 2 years follows up for each week. so we look for method programmatical import call data here or change timing **### is there way to import call data directly in REDcap in Survey Invitation Log?**

**Comment by sburns** [comment]
I really can't say, this is a far newer feature than when I was working with REDCap full time. You should look at the API docs by clicking on the "API" link in the lower left of this screenshot and see if there's anything available with respect to survey invitations

**Comment by remifrazierucsf** [comment]
There is not a method for this in the current API.

**Comment by sburns** [comment]
If it's not the API, there's nothing PyCap can do for now.
