### ISSUE TITLE
Can't import blank ("") values into fields

### ISSUE THREAD

**Issue by DanielTsuha** [redcap-tools/PyCap#99]
I couldn't figure out how to import blank values into REDCap fields.

I have tried:
> data = project.export_records()
> data[0]["result"] = ""    or   data[0]["result"] = None
> response = project.import_records(data)

I also tried:
`response = project.import_records(data, overwrite=True)`

However, none of the above worked.
There were no errors, but the original values were not updated.
Is it doable?

**Comment by sburns** [comment]
How do you know it's not working? Were there previously values that are not being overwritten?

**Comment by DanielTsuha** [comment]
> How do you know it's not working? Were there previously values that are not being overwritten?

Hi **sburns**. Yes, the values entered previously are not being overwritten.
The field is of text type, number validation and not required.

If the REDCap form field already has a value of '88', for example, the code posted above does not overwrite the '88' value. No error messages are shown. If the code is changed to `data[0]["result"] = 0` it will work, but it's not right.

However, I'm able manually erase the value in order to in order to have a blank/empty field in the REDCap project webpage.

**Comment by nicklecompteBCH** [comment]
You need to provide a non-default value for the `overwrite` parameter in `import_records` - namely, "overwrite."

```
def import_records(self, to_import, overwrite='normal', format='json',
        return_format='json', return_content='count',
        date_format='YMD', force_auto_number=False):
```

So this should work (though I have not tested it):

```
data = project.export_records()
data[0]["result"] = "" or data[0]["result"] = None
response = project.import_records(data, overwrite="overwrite")
```

From the REDCap API documentation:

> overwriteBehavior
normal - blank/empty values will be ignored [default]
overwrite - blank/empty values are valid and will overwrite data

**Comment by DanielTsuha** [comment]
Hi **nicklecompteBCH**, your tip worked great.
I'm closing this issue.

Thanks a lot!
